site_name: FirecrackerSharp
site_url: https://firecrackersharp.github.io
theme:
  name: material
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
